# -*- coding: utf-8 -*-
"""Day-14

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_l6u7VYBW1mYkFmBHsTp5r1eYIBxls9V
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

df = pd.read_csv('/content/tripadvisor_hotel_reviews.csv')
df.head()

df['Rating'].value_counts()

def ratings(rating):
  if rating>3 and rating<=5:
    return 'Positive'
  elif rating>0 and rating<=3:
    return 'Negative'

df['Rating'] = df['Rating'].apply(ratings)

plt.pie(df['Rating'].value_counts(),
        labels=df['Rating'].unique().tolist(),
        autopct='%1.1f%%')
plt.show()

length = len(df['Review'][0])
print(f'Length of a sample review: {length}')

df['Length'] = df['Review'].str.len()
df.head()

word_count=df['Review'][0].split()
print(f'Word Count in a sample review: {len(word_count)}')

def word_count(review):
  review_list = review.split()
  return len(review_list)

df['Word_count'] = df['Review'].apply(word_count)
df.head()

df['mean_word_length'] = df['Review'].map(lambda rev: np.mean([len(word) for word in rev.split()]))
df.head()

from nltk import tokenize
np.mean([len(sent) for sent in tokenize.sent_tokenize(df['Review'][0])])

df['mean_sent_length'] = df['Review'].map(lambda rev: np.mean([len(sent) for sent in tokenize.sent_tokenize(rev)]))